version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  PostgreSQL:
    image: postgres:13.0-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data/
    env_file:
      - ./.env

  Django:
    image: amirsvc/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media_backend/
    depends_on:
      - PostgreSQL
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html_backend/
    depends_on:
      - Django

volumes:
  postgresql:
  static_value:
  media_value:
